# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.11.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: dependencies installing
          command: yarn

      - run:
          name: dependencies for CI
          command: yarn add bithound coveralls mocha-lcov-reporter

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: test
          command: yarn test-ci

      # run tests on docker!
      - run:
          name: test on docker
          command: yarn test-docker

      # run coverage report
      - run:
          name: coverage
          command: yarn coverage-ci

      # run quality code with bithound
      - run:
          name: bithound
          command: yarn bithound

